server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /products {
        proxy_pass http://service-backend:8000;
    }

    location /orders {
        proxy_pass http://service-backend:8000;
    }

    location /health {
        proxy_pass http://service-backend:8000;
    }

    location /ready {
        proxy_pass http://service-backend:8000;
    }
}
