apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment_backend.yml
  - deployment_frontend.yaml
  - deployment_postgress.yaml
  - name_space.yaml
  - service_backend.yaml
  - service_frontend.yaml
  - service_postgres.yaml
  - sealedsecret-postgres.yaml
  - sealedsecret-backend.yaml



