---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config-backend
  namespace: miniorders
spec:
  encryptedData:
    DATABASE_URL: AgAL0X4fZ2gL3aR0DCdqbg+7KftSOi4I3GbM7jOKpikSqhjHNDS+iFI1bnXjjZ4tpwtrE7iQOYBIoIAgT29tlX60NWephj1qCvfVJtKtVwGOPF7o/JVXyjP7NHXo2pufZig9YARuOfpCHUWnCpdoQN39mo90mQcLUoLkZCLVA/jeefb6HE49sCu5oNQEg8sajDz5aqZqm+euz8pBFilPzShG6PqrNzvhbvwRydOv2I5kEqrGLWioLmuXbuaV7FlyKfRu+YcN2h2Ic2KdyEwlBqzzblxpmlw5M198qL+B7NXHuJ7dzbgkqvH7If3KzgwvJC1V0bECKSos/t/44Su56xvr5EhNDKYpEeKI3tyPL7kaybBNhtS1wKuOlxOWIK6edNCnjAEilqB6e4GiOrWgyXIohqDGgBYmWNGjppoCglmXzZkesgHtWyCAqJWVaAhSly9hMvWWWTEu/n6b766G05kPZpRJ+NOZ02lWW7HpXtzYerdMlzYp3EpUpMdg33gJGr3M4aQ443yMcVtcp7enhGmOBpbjIHgLmY/w77RsxzO+rMRJbC29R4oEYAVrue4KwuKu/5JYT0si50GyAU8eh+p+wI7jCZ8Dl86OuGdMvTfo5Sy5aCA3gSbtRhrAvGT/vBtmVYCIcVpsUIRq0zf2wllTkwHG/ZTCgPFB/nz5nkLvlz4xBzrL0VdRmVqDZ2ORAUXkw59TUfhv205AqGdgF7qygAk+Nt2HsasEF50aLzIWiezQr9KLQ1/CMeSW9fBQb/VO
  template:
    metadata:
      name: config-backend
      namespace: miniorders
